POST  http://localhost:3000/api/transactions
Content-Type: application/json
{
  "description": "editar intento",
  "date": "2025-10-26T12:00:00Z",
  "type": "income",
  "amount": 5,
  "accountId": 2
}